project:
  type: website
  output-dir: docs
  
lang: en

execute:
  freeze: false
  cache: false
  
format:
  html:
    theme:
      light: minty
      dark: darkly
    callout-appearence: simple
    css: assets/styles.css
    toc: true
    toc-depth: 4
    smooth-scroll: true
    highlight-style: atom-one
    number-sections: true
    number-depth: 4
    pagetite: "{{< var meta.title>}}"

website:
  repo-url: https://github.com/UCLPG-MSC-SGDS/GEOG0114
  repo-actions: [issue]
  page-navigation: true
  search:
    location: sidebar
    type: overlay
  sidebar:
    style: floating
    collapse-level: 2
    logo: images/general/ucl_logo1.png
    logo-href: https://www.ucl.ac.uk/module-catalogue/modules/GEOG0114
    tools:
      - icon: github
        href: https://github.com/UCLPG-MSC-SGDS/GEOG0114
    contents:
      - section: "Module Overview"
        contents: 
          text: "Welcome"
          file: 00-module_overview.qmd
      - section: "Getting Started"
        contents:
          - 01-reading_list.qmd
          - 02-installation.qmd
      - section: "Foundation & Theory"
        contents:
          - 03-spatial_analysis_for_data_science.qmd
          - 04-graphical_representation.qmd
          - 05-spatial_autocorrelation.qmd
      - section: "Raster-Based Analysis"
        contents:
          - 06-suitability_mapping_AHP.qmd
          - 07-suitability_mapping_Niche.qmd
          - 08-geostatistics_kriging.qmd
      - section: "Video Archive"
        contents:
          - 11-video_achives.qmd



